/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.LoginDAO;
import DAO.UsuarioDAO;
import DTO.UsuarioDTO;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;




public class frmLoginVIEW extends javax.swing.JFrame {

    /**
     * Creates new form frmLoginVIEW
     */
    public frmLoginVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome_Usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSenha_Usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPerfil = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Login");
        getContentPane().setLayout(null);

        jLabel1.setText("Nome do Usuário");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(32, 16, 330, 20);
        getContentPane().add(txtNome_Usuario);
        txtNome_Usuario.setBounds(32, 44, 257, 30);

        jLabel2.setText("Senha do Usuário");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 80, 310, 30);
        getContentPane().add(txtSenha_Usuario);
        txtSenha_Usuario.setBounds(32, 117, 257, 30);

        jLabel3.setText("Perfil");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(32, 148, 330, 20);
        getContentPane().add(txtPerfil);
        txtPerfil.setBounds(32, 173, 257, 30);

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(32, 221, 100, 30);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(279, 16, 0, 0);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(200, 220, 100, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/Imagens/estetica.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 400, 300);

        jButton2.setText("jButton2");
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 260, 73, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
      
        try {
                String nome_usuario, senha_usuario, perfil;
        
        nome_usuario = txtNome_Usuario.getText();
        senha_usuario = txtSenha_Usuario.getText();
        perfil = txtPerfil.getText();
        
        UsuarioDTO objusuariodto = new UsuarioDTO();
        objusuariodto.setNome_usuario(nome_usuario);
        objusuariodto.setSenha_usuario(senha_usuario);
        objusuariodto.setPerfil(perfil);
        
            LoginDAO objlogindao = new LoginDAO();
            ResultSet rsusuariodao = objlogindao.autenticacaoUsuario(objusuariodto);
            
            if(rsusuariodao.next()) {
            
            frmPrincipalVIEW objfrmprincipalview =  new frmPrincipalVIEW();
            objfrmprincipalview.setVisible(true);
            
            
                dispose();
            
            }
            
            else{
            
            JOptionPane.showMessageDialog(null, "Usuario, Senha ou Perfil inválido");
            
            }
            
            
            
            
        
        
        } catch (SQLException erro) {
            
            JOptionPane.showMessageDialog(null,"FRMLOGINVIEW" +  erro);
        }
        
        
        
                
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
    
         String cadastronome_usuario, cadastrosenha_usuario, cadastroperfil;
         
         cadastronome_usuario = txtNome_Usuario.getText();
         cadastrosenha_usuario = txtSenha_Usuario.getText();
         cadastroperfil = txtPerfil.getText();
         
         UsuarioDTO objusuariodto = new UsuarioDTO();
         objusuariodto.setCadastronome_usuario(cadastronome_usuario);
        objusuariodto.setCadastrosenha_usuario(cadastrosenha_usuario);
        objusuariodto.setCadastroperfil(cadastroperfil);
        
        UsuarioDAO objusuariodao = new UsuarioDAO();
        objusuariodao.cadastarPerfil(objusuariodto);
        
        
        
         
        
        
        
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLoginVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLoginVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLoginVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLoginVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLoginVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtNome_Usuario;
    private javax.swing.JTextField txtPerfil;
    private javax.swing.JTextField txtSenha_Usuario;
    // End of variables declaration//GEN-END:variables
}

